fastlane_version '1.39.0'

default_platform :ios

platform :ios do
  desc 'Upload this version to HockyApp.'
  lane :hockey do
    # Version bump.
    increment_build_number
    commit_version_bump
    add_git_tag prefix: 'v'
    push_to_git_remote

    # Build the application.
    gym(
      scheme: 'Runway',
      configuration: 'Release',
      clean: true,
      use_legacy_build_api: true
    )

    # Upload to HockeyApp.
    hockey(
      api_token: ENV['HOCKEYAPP_API_TOKEN'],
      teams: 'Runway',
      notify: '1',
      status: '2'
    )
  end
end
